# Generated by Django 6.0.3 on 2026-03-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
